# Generated by Django 3.1.4 on 2020-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='t',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
